[package]
name = "pyru-graphql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1", features = ["full"]}

axum = "0.3"

async-graphql = "2"
async-graphql-axum = "2"